### ISSUE TITLE
ActiveRecord::ConnectionTimeoutError with Shoryuken

### ISSUE THREAD

**Issue by mr-sudaca** [tsukasaoishi/ebisu_connection#6]
Hello @tsukasaoishi, I came across with this issue while moving from [Makara](https://github.com/taskrabbit/makara) to your gem

```
ActiveRecord::ConnectionTimeoutError: could not obtain a database connection within 5.000 seconds (waited 5.012 seconds)
```

I have installed [Shoryuken](https://github.com/phstc/shoryuken) to process som SQS queues, but everytime I run them I have the error above

I've tried some solutions, like [this one](https://engineering.sharethrough.com/blog/2015/08/24/migrating-from-resque-to-sidekiq/) (since Shoryuken is based on Sidekiq) but nothing worked. 

Don't know if you had this problem in the past, maybe there's a workaround for it

Thanks a lot for your help

**Comment by mr-sudaca** [comment]
i've got it working by closing replica connections at the end of each call, something like:
```ruby
    def perform(sqs_msg, body)
      execute_perform(sqs_msg, body)
    ensure
      ActiveRecord::Base.replica_connection.close
      ActiveRecord::Base.connection.close
    end
```

now it's working without problems.

edit: typo

**Comment by tsukasaoishi** [comment]
This error occurs when all the connections in the Rails connection pool are in use, and when a new thread requests a connection.
I think that it is not a bug but a matter of setting.
The following sites may be helpful for you.
https://devcenter.heroku.com/articles/concurrency-and-database-connections

**Comment by froveda** [comment]
@mr-sudaca thank you very much! As usual you came up with the best solution. Months I've been trying to find a solution for this error (even when I don't use ebisu), and your code fixed the error finally! Thank you very much!
